config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :images do
      collection { post :upload_image } end

  match 'sendmail',     :controller => :carts,  :to => :sendmail, :via => :get, :as => :send_mail
  match 'checkout',     :controller => :carts,  :to => :checkout, :via => :get, :as => :checkout
  match 'add/:id',      :controller   =>:carts, :to => :add,     :via  => :get,     :as =>:cart_add
  match 'cart/index',   :controller   =>:carts, :to => :index,   :via  => :get,     :as =>:cart_index
  match 'cart/destroy/:id', :controller   =>:carts, :to => :destroy, :via => :get,  :as => :cart_destroy
  match 'remove/:id',   :controller   =>:carts, :to => :remove,   :via => :delete, :as => :cart_remove
  match 'update/:id',   :controller => :carts, :to => :update, :via => :put, :as => :cart_update
  match 'detail/:id',   :controller => :products, :to => :detail, :via => :get, :as => :product_detail

  root  'products#show'
  match 'search', :controller => :products, :to => :index, :via => :post, :as => :search_product

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get', as: 'about'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/uploadfile', to: 'upload#uploadfile', via: 'post'

  get 'static_pages/home'
  get 'static_pages/help'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_modal_product.html.erb
<% @products.each do |product| %>
  <div class="show-product">
    <h4 class="name-product">
      <%= product.title %>
    </h4>
    <div class="row">
      <div class="span3">
        <%= gravatar_for_product(product.image, size: 200) %>
        <!--        <img src=<%= product.image %> class="img-responsive" alt="Responsive image" >-->
      </div>
      <div class="span6">
        <h4 class="description-header" >Description: </h4>
        <p class="description-container">
          <%= raw(product.description.truncate(100)) %>
        </p>
        <h4 class="description-header" >Price: </h4>
        <h5><%= product.price %> $</h5>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-medium btn-primary" data-toggle="modal" data-target=<%= "#myModal#{product.id}"%>><b>Quick view</b></button>
        <b><%= link_to "Detail",  product_detail_path(product.id), class: "btn btn-medium btn-primary" %></b>
        <b><%= link_to "Add to Cart", cart_add_path(product.id), class: "btn btn-medium btn-primary" %></b>

        <!-- Modal -->
        <div class="modal fade" id=<%= "myModal#{product.id}"%> tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h4 id="title-quick">
                  <%= product.title %>
                </h4>
              </div>
              <div class="modal-body">
                <div id="button-add-cart-quick">
                  <%= gravatar_for_product(product.image, size: 300) %>
                  <%= link_to image_tag("http://etc-mysitemyway.s3.amazonaws.com/icons/legacy-previews/icons/glossy-silver-icons-business/080954-glossy-silver-icon-business-cart2.png", :id => "img-add-cart"), cart_add_path(product.id) %>
                </div>
                <h4 id="description-quick">Description: </h4>
                <div id="content-description-quick">
                  <%= raw(product.description.truncate(200)) %>
                </div>
                <div id="price-quick">
                  <h5>Price: <%= product.price %> $</h5>
                </div>
                <div id="amount-quick">
                  <h5>Amount: <%= product.amount %></h5>
                </div>
                <div id="category-quick">CATEGORY:
                  <%= @categories.find_by(id: product.category_id).title %>
                </div>
              </div>
              <div class="modal-footer">
                <div id="author-quick">
                  <b>Author: </b>
                  <%= product.author %>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- End Modal -->
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_nav_menu.html.erb
<a href="<%= root_path %>"><marquee><h1 id="menu-category"><i>Category</i><h1></marquee></a>
<ul class="nav nav-pills nav-stacked">
	<% @categories.each do |category_tmp| %>
	<% if @category.blank? then %>
			<li class="menu-item"><a href=<%= "/categories/#{category_tmp.id}"%> ><b><%= category_tmp.title %></b></a></li>
		<% else %>
			<% if (@category.id == category_tmp.id) then %>
				<li class="active menu-item" ><a href=<%= "/categories/#{category_tmp.id}"%> ><b><%= category_tmp.title %></b></a></li>
			<% else %>
				<li class="menu-item"><a href=<%= "/categories/#{category_tmp.id}"%> ><b><%= category_tmp.title %></b></a></li>
			<% end %>
		<% end %>
	<% end %>
</ul>

app/views/shared/_product_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :price %>
    <%= number_field(:product, :price, in: 0.1..10000.0, step: 0.1) %>

    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Description for new product!!!" %>

    <%= f.label :amount %>
    <%= number_field(:product, :amount, in: 1.0..1000.0, step: 1) %>

    <%= f.label :isbn %>
    <%= f.text_field :isbn %>

    <%= f.label :category_id %>
    <%= collection_select(:product, :category_id, Category.all, :id, :title) %>

    <%= f.label :image %>
    <%= f.text_area :image %>

  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_show_product_form.html.erb
<div class="row">
	<div class="span2">
		<%= render 'shared/nav_menu' %>
	</div>
	<div class="span10">
		<%= render 'shared/modal_product' %>
		<%= will_paginate @products %>
	</div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.products.count, "products") %>
</span>