config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :images do
      collection { post :upload_image } end

  match 'sendmail',     :controller => :carts,  :to => :sendmail, :via => :get, :as => :send_mail
  match 'checkout',     :controller => :carts,  :to => :checkout, :via => :get, :as => :checkout
  match 'add/:id',      :controller   =>:carts, :to => :add,     :via  => :get,     :as =>:cart_add
  match 'cart/index',   :controller   =>:carts, :to => :index,   :via  => :get,     :as =>:cart_index
  match 'cart/destroy/:id', :controller   =>:carts, :to => :destroy, :via => :get,  :as => :cart_destroy
  match 'remove/:id',   :controller   =>:carts, :to => :remove,   :via => :delete, :as => :cart_remove
  match 'update/:id',   :controller => :carts, :to => :update, :via => :put, :as => :cart_update
  match 'detail/:id',   :controller => :products, :to => :detail, :via => :get, :as => :product_detail

  root  'products#show'
  match 'search', :controller => :products, :to => :index, :via => :post, :as => :search_product

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get', as: 'about'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/uploadfile', to: 'upload#uploadfile', via: 'post'

  get 'static_pages/home'
  get 'static_pages/help'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
    @products = Product.all
  end

  def add
    session[:cart] ||= []
    check = false
    session[:cart].each do |a|
      if a["product_id"] == params[:id] then
        a["amount"] = a["amount"] + 1
        check = true
      end
    end

    session[:cart]. push ({"product_id" => params[:id], "amount" => 1}) unless check

    product_title = Product.find(params[:id]).title
    flash[:success] = "add success product \"#{product_title}\" to your cart"
    redirect_to root_path
  end

  def remove
    product_title = Product.find(params[:id]).title
    session[:cart].each do |a|
      if a["product_id"] == params[:id] then
        a["amount"] = 0
      end
    end
    flash[:success] = "delete success product \"#{product_title}\" from your cart"
    redirect_to cart_index_path
  end

  def update
    product_title = Product.find(params[:id]).title
    if params[:amount][:quantity].blank? then
      flash[:error] = "edit fail quantity of product \"#{product_title}\" "
    else
      quantity = params[:amount][:quantity].to_i
      session[:cart].each do |a|
        if a["product_id"] ==  params[:id] then
          a["amount"] = quantity
        end
      end
      flash[:success] = "edit success quantity of product \"#{product_title}\" "
    end

    redirect_to cart_index_path
  end

  def sendmail
    @products = Product.all
  end

  def checkout
    @products = []
    @email = params[:email]
    @total_money = 0;
    @allproduct = Product.all
    session[:cart].each do |a|
      @products.push ({"product_id" => a["product_id"], "amount" => a["amount"]})
      @total_money += Product.all.find(a["product_id"]).price * a["amount"]
    end
    session.clear
    Sendmail.sendmail(@products, @email, @total_money).deliver
  end

  def destroy
    session.clear
    if params[:id] == "0" then
      flash[:success] = "Cancel your cart success"
    else
      flash[:success] = "Thank you for shopping"
    end

    redirect_to root_path
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/add.html.erb
add successfull

app/views/carts/checkout.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Money</th>
    </tr>
    </thead>
    <tbody>
      <% i = 3
        count = 0
      %>
      <% @products.each do |a| %>
        <% if a["amount"] != 0 then %>
          <% price = @allproduct.find(a["product_id"]).price%>
          <% string_test = ""
            if i == 0 then
              string_test = ""
            elsif i == 1 then
              string_test = "active"
            elsif i == 2 then
              string_test = "info"
            else
              string_test = "warning"
              i = 0
            end %>
          <tr class=<%= string_test %>>
            <td><%= a["product_id"] %></td>
            <td>
              <b><%=h strip_tags(@allproduct.find(a["product_id"]).title.truncate(30)) %></b></td>
            <td><%=  price %> $ </td>
            <td><%= a["amount"] %></td>
            <td><%= a["amount"] * price %> $ </td>
            <%
              count += a["amount"]
            %>
          </tr>
          <% i += 1%>
        <% end %>
      <% end %>
      <tr class="success">
        <td><b>Total</b></td>
        <td></td>
        <td></td>
        <td><b><%= count %></b></td>
        <td><b><i><%= @total_money.round(3) %> $</i></b> </td>
      </tr>
    </tbody>
  </table>
  <div class="notify-when-checkout">
    <h4 class="checkout-message">Total money you need pay: <b><%= @total_money.round(3)%> $</b> for <%= pluralize(count, "product") %></h4>
    <h4 class="checkout-message">We have send message about your cart to email: <u><b><i><%= @email %></i></b></u></h4>
    <h3 class="checkout-message">Thank you for shopping!!!</h3>
  </div>
  <%= button_to cart_destroy_path(1),class: "btn btn-warning", :method => :get do %><i>Exit</i>
  <% end %>
</div>

app/views/carts/destroy.html.erb
Delete successfull

app/views/carts/index.html.erb
<div class="table-responsive">
  <table class="table table-hover">
  	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Price</th>
			<th>Amount</th>
			<th>Money</th>
			<th rowspan="2">Edit</th>
			<th>Remove</th>
		</tr>
		</thead>
		<tbody>
			<% i = 3
				total_money = 0
			%>
			<% session[:cart].each do |a| %>
				<% if a["amount"] != 0 then %>
					<% price = @products.find(a["product_id"]).price%>
					<% string_test = ""
						if i == 0 then
							string_test = ""
						elsif i == 1 then
							string_test = "active"
					 	elsif i == 2 then
					 		string_test = "info"
					 	else
							string_test = "warning"
							i = 0
						end %>
					<tr class=<%= string_test %>>
						<td><%= a["product_id"] %></td>
						<td>
							<b><%=h strip_tags(@products.find(a["product_id"]).title.truncate(30)) %></b></td>
						<td><%=  price %> $ </td>
						<td><%= a["amount"] %></td>
						<td><%= a["amount"] * price %> $ </td>
						<td>
							<%= form_tag cart_update_path(a["product_id"], value: params[:amount]), :method => :put do %>
    						<%= number_field(:amount, :quantity, in: 1.0..200.0, step: 1) %>
    						<%= button_tag class: "close", data: { confirm: 'Are you sure to edit quantity of product?'} do %><i class="icon-ok"></i>
								<% end %>
							<% end %>
						</td>
						<td>
						<%= button_to cart_remove_path(a["product_id"]),class: "btn btn-danger", :method => :delete,  data: { confirm: 'Are you sure to delete product?'} do %><i class="icon-trash"></i>
						<% end %>
						</td>
						<% total_money += a["amount"] * price %>
					</tr>
					<% i += 1%>
				<% end %>
			<% end %>
			<tr class="success">
				<td><b>Total</b></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td></td>
				<td><b><i><%= total_money.round(3) %> $</i></b> </td>
			</tr>
		</tbody>
	</table>
	<div>
		<%= button_to cart_destroy_path(0),class: "btn btn-warning", :method => :get,  data: { confirm: 'Are you sure to cancel your cart?'} do %><i>Cancel</i>
		<% end %>
		<%= button_to send_mail_path,class: "btn btn-info", :method => :get,  data: { confirm: 'Are you sure continue?'} do %><i>Continue</i>
		<% end %>
	</div>
</div>

app/views/carts/remove.html.erb
remove successfull

app/views/carts/sendmail.html.erb
<div class="table-responsive">
  <table class="table table-hover">
    <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Money</th>
    </tr>
    </thead>
    <tbody>
      <% i = 3
        total_money = 0
      %>
      <% session[:cart].each do |a| %>
        <% if a["amount"] != 0 then %>
          <% price = @products.find(a["product_id"]).price%>
          <% string_test = ""
            if i == 0 then
              string_test = ""
            elsif i == 1 then
              string_test = "active"
            elsif i == 2 then
              string_test = "info"
            else
              string_test = "warning"
              i = 0
            end %>
          <tr class=<%= string_test %>>
            <td><%= a["product_id"] %></td>
            <td>
              <b><%=h strip_tags(@products.find(a["product_id"]).title.truncate(30)) %></b></td>
            <td><%=  price %> $ </td>
            <td><%= a["amount"] %></td>
            <td><%= a["amount"] * price %> $ </td>
            <% total_money += a["amount"] * price %>
          </tr>
          <% i += 1%>
        <% end %>
      <% end %>
      <tr class="success">
        <td><b>Total</b></td>
        <td></td>
        <td></td>
        <td></td>
        <td><b><i><%= total_money.round(3) %> $</i></b> </td>
      </tr>
    </tbody>
  </table>

  <%= form_tag checkout_path(), :method => :get do %>
    <% if signed_in? then %>
      <%= label_tag :email %>
      <%= email_field_tag :email, current_user.email , class: "input-xxlarge" %>
      <%= button_tag class: "btn btn-info", data: { confirm: 'Are you sure to check out your cart?'} do %><i>Check out</i>
      <% end %>
    <% else %>
      <%= label_tag :email %>
      <%= email_field_tag :email, "Please enter your mail!!!" , class: "input-xxlarge" %>
      <%= button_tag class: "btn btn-info", data: { confirm: 'Are you sure to check out your cart?'} do %><i>Check out</i>
      <% end %>
    <% end %>
  <% end %>

  <%= button_to cart_destroy_path(0),class: "btn btn-warning", :method => :get,  data: { confirm: 'Are you sure to cancel your cart?'} do %><i>Cancel</i>
  <% end %>
</div>

app/views/carts/update.html.erb
Update succesfull <%= @result %>