config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :products
  resources :sessions, only: [:new, :create, :destroy]
  resources :categories
  resources :images do
      collection { post :upload_image } end

  match 'sendmail',     :controller => :carts,  :to => :sendmail, :via => :get, :as => :send_mail
  match 'checkout',     :controller => :carts,  :to => :checkout, :via => :get, :as => :checkout
  match 'add/:id',      :controller   =>:carts, :to => :add,     :via  => :get,     :as =>:cart_add
  match 'cart/index',   :controller   =>:carts, :to => :index,   :via  => :get,     :as =>:cart_index
  match 'cart/destroy/:id', :controller   =>:carts, :to => :destroy, :via => :get,  :as => :cart_destroy
  match 'remove/:id',   :controller   =>:carts, :to => :remove,   :via => :delete, :as => :cart_remove
  match 'update/:id',   :controller => :carts, :to => :update, :via => :put, :as => :cart_update
  match 'detail/:id',   :controller => :products, :to => :detail, :via => :get, :as => :product_detail

  root  'products#show'
  match 'search', :controller => :products, :to => :index, :via => :post, :as => :search_product

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get', as: 'about'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/uploadfile', to: 'upload#uploadfile', via: 'post'

  get 'static_pages/home'
  get 'static_pages/help'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="<%= root_path %>">Venshop demo</a>
    by Minh Tuan
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner" id="header-color">
    <div class="container">
      <nav>
      <a href="<%= root_path %>"><img id="logo-img" src="http://scoobybook.com/images/world.png"><span id="logo">Venshop</span></a>
        <ul class="nav pull-right">
          <li>
            <a href="<%= root_path %>" id="your-cart"><img id="your-home-icon" src ="http://www.catanduanestribune.com/App_Themes/CTribune/images/buttons/home.png"></a>
          </li>
          <li>
            <% number_product = 0
              session[:cart] ||= []
              session[:cart].each do |a|
                number_product += a["amount"]
              end
            %>
          <li><a href="<%= cart_index_path %>" id="your-cart"><img id="your-cart-icon" src ="http://www.timothyotooles.com/images/shoppingcart_icon-white.gif">  <span class="badge" id="face-not"><%= number_product %></span></a></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img id="your-cart-icon" src ="http://www.silvermanmorrison.com/wp-content/uploads/2014/07/manager-256.png">
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><a href="<%= signin_path %>" id="your-cart"><img id="your-home-icon" src ="http://www.iconsdb.com/icons/preview/white/login-xxl.png"></a></li>
          <% end %>
        </ul>
      </nav>
    </div>
    <div class="container">
      <%= form_tag search_product_path, :id => "form-search", :class => "pull-down  navbar-search", :method => :post do %>
      <p>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], :class => "search-query input-medium" %>
          <%= button_to "Search", :name => nil, :id => "search-button", :class => "add-on" do %>
            <i class="icon-search"></i>
          <% end %>
        </div>
      </p>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link rel="icon" href="http://www.fontsaddict.com/images/icons/png/thumb/14280.png">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <style>
      .nav-stacked {
        font-family: 'Tangerine', serif;
        font-size: 30px;
      }
      h4 {
        font-family: 'Pacifico', cursive;
        color: #333333;
        font-size: 20px;
      }
      p {
        /*font-family: 'Playfair Display', serif;*/
        font-family: Helvetica,Arial,'lucida grande',tahoma,verdana,arial,sans-serif;
      }
    </style>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <br/><br/><br/>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
    <div class="container">

      <div connections="10" data-show-border="false" data-stream="false" data-header="false" data-show-faces="true" data-colorscheme="light" data-height="232" data-href="https://www.facebook.com/Lawliet.Tuan" class="fb-like-box fb_iframe_widget" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=334341610034299&amp;color_scheme=light&amp;connections=10&amp;header=false&amp;height=232&amp;href=https%3A%2F%2Fwww.facebook.com%2Fprestashop&amp;locale=en_US&amp;sdk=joey&amp;show_border=false&amp;show_faces=true&amp;stream=false"><span style="vertical-align: bottom; width: 300px; height: 232px;"><iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FLawliet.Tuan&amp;width&amp;layout=standard&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true"></iframe></span></div>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>